settings: &SETTINGS
  adapter: mysql
  reconnect: false
  pool: 5
  username: railsnoob
  password: railsnoob
  socket: /tmp/mysql.sock

development:
  database: railsnewbie_dev
  <<: *SETTINGS

test: &TEST
  database: railsnewbie_test
  <<: *SETTINGS

production:
  database: railsnewbie_prod
  <<: *SETTINGS

# this causes some rake db:* tasks to complain.
# please disregard test-database related whining.
cucumber:
  <<: *TEST
